project:
  type: website
  output-dir: docs

website:
  title: "Travels"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog Posts

format:
  html:
    theme: 
      - mystyles.scss
    mainfont: Lato
    toc: true

editor: visual

